#include QMK_KEYBOARD_H

/*
 * This matrix was generated by qmk json2c. You may or may not want to
 * edit it directly.

    \[0\] = LAYOUT_reviung39\()?((?:[\w()]+, ){11}(?:[\w()]+, ))

    TODO: Caps Lock LED indicator
    TODO: Limit the number of LED modes to Breathing and Steady-state
 */


const uint16_t PROGMEM keymaps[][MATRIX_ROWS][MATRIX_COLS] = {
    [0] = LAYOUT_reviung39(
        LALT_T(KC_TAB), KC_Q, KC_W, KC_E, KC_R, KC_T, 	KC_Y, KC_U, KC_I, KC_O, KC_P, KC_BSPC,
        LCTL_T(KC_CAPS), KC_A, KC_S, KC_D, KC_F, KC_G, 	KC_H, KC_J, KC_K, KC_L, KC_SCLN, RCTL_T(KC_QUOT),
        KC_LSFT, KC_Z, KC_X, KC_C, KC_V, KC_B, 	KC_N, KC_M, KC_COMM, KC_DOT, KC_SLSH, KC_RSFT,
        MO(1), LT(3,KC_SPC), MO(2)
    ),
    [1] = LAYOUT_reviung39(
        KC_ESC,  KC_1,  KC_2,  KC_3,  KC_4,  KC_5, 	            KC_6,    KC_7,    KC_8,    KC_9,    KC_0,    KC_DEL,
        KC_CAPS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS,   KC_MINS, KC_EQL,  KC_LBRC, KC_RBRC, KC_BSLS, KC_GRV,
        KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, 	KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS,
        KC_ENT,  KC_TRNS, KC_TRNS
    ),
    [2] = LAYOUT_reviung39(
        KC_ESC,  KC_1,  KC_2,  KC_3,  KC_4,  KC_5, 	            KC_6,    KC_7,    KC_8,    KC_9,    KC_0,     KC_DEL,
        KC_LGUI, KC_TRNS, KC_TRNS, KC_INS,  KC_HOME, KC_PGUP, 	KC_LEFT, KC_DOWN, KC_UP,   KC_RGHT, KC_TRNS,  KC_RGUI,
        KC_TRNS, KC_TRNS, KC_TRNS, KC_DEL,  KC_END,  KC_PGDN,   KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS,  KC_TRNS,
        KC_TRNS, KC_TRNS, KC_TRNS
    ),
    [3] = LAYOUT_reviung39(
        KC_F1,   KC_F2,   KC_F3,   KC_F4,   KC_F5,   KC_F6,     KC_F7,   KC_F8,   KC_F9,   KC_F10,  KC_F11,  KC_F12,
        KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, 	KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS,
        KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, 	KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS,
        KC_LSFT, KC_TRNS, KC_ENT
    ),
    [4] = LAYOUT_reviung39(
        KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, 	KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS,
        KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, 	KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS,
        KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, 	KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS,
        KC_TRNS, KC_TRNS, KC_TRNS
    ),
};
