#include QMK_KEYBOARD_H

enum layer_names {
    _BASE,
    _LOWER,
    _RAISE,
    _ADJUST,
    _FN,
    _RESET
};

#define LOWER  MO(_LOWER)
#define RAISE  MO(_RAISE)
#define ADJUST MO(_ADJUST)

/*
 * This matrix was generated by qmk json2c. You may or may not want to
 * edit it directly.

    \[_BASE\] = LAYOUT_reviung39\()?((?:[\w()]+, ){11}(?:[\w()]+, ))
 */


const uint16_t PROGMEM keymaps[][MATRIX_ROWS][MATRIX_COLS] = {
    [_BASE] = LAYOUT_reviung39(
        LALT_T(KC_TAB), KC_Q, KC_W, KC_E, KC_R, KC_T, 	KC_Y, KC_U, KC_I, KC_O, KC_P, KC_BSPC,
        LCTL_T(KC_CAPS), KC_A, KC_S, KC_D, KC_F, KC_G, 	KC_H, KC_J, KC_K, KC_L, KC_SCLN, RCTL_T(KC_QUOT),
        KC_LSFT, KC_Z, KC_X, KC_C, KC_V, KC_B, 	KC_N, KC_M, KC_COMM, KC_DOT, KC_SLSH, KC_RSFT,
        LOWER, LT(4,KC_SPC), RAISE
    ),
    [_RAISE] = LAYOUT_reviung39(
        KC_LALT, KC_1, KC_2, KC_3, KC_4, KC_5, 	KC_6, KC_7, KC_8, KC_9, KC_0, KC_RALT,
        KC_LGUI, KC_NO, KC_NO, KC_INS, KC_HOME, KC_PGUP, 	KC_LEFT, KC_DOWN, KC_UP, KC_RGHT, KC_NO, KC_LGUI,
        KC_TRNS, KC_NO, KC_NO, KC_DEL, KC_END, KC_PGDN, 	KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_ENT,
        ADJUST, KC_ENT, KC_TRNS
    ),
    [_LOWER] = LAYOUT_reviung39(
        KC_ESC, KC_1, KC_2, KC_3, KC_4, KC_5, 	KC_6, KC_7, KC_8, KC_9, KC_0, KC_DEL,
        KC_CAPS, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, 	KC_MINS, KC_EQL, KC_LBRC, KC_RBRC, KC_BSLS, KC_GRV,
        KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, 	KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO,
        KC_TRNS, KC_ENT, ADJUST
    ),
    [_ADJUST] = LAYOUT_reviung39(
        RGB_VAI, RGB_SAI, RGB_HUI, RGB_MOD, KC_NO, RGB_TOG, 	TO(0), KC_NO, KC_NO, KC_NO, KC_NO, KC_NO,
        RGB_VAD, RGB_SAD, RGB_HUD, RGB_RMOD, KC_NO, KC_NO, 	KC_NO, KC_NO, KC_NO, CG_NORM, GUI_OFF, GUI_ON,
        MO(5), KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, 	KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO,
        KC_TRNS, KC_NO, KC_TRNS
    ),
    [_FN] = LAYOUT_reviung39(
        KC_F1, KC_F2, KC_F3, KC_F4, KC_F5, KC_F6, 	KC_F7, KC_F8, KC_F9, KC_F10, KC_F11, KC_F12,
        KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, 	KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO,
        LCTL(LGUI(KC_LEFT)), LCTL(LGUI(KC_RIGHT)), KC_NO, KC_NO, KC_NO, KC_NO, 	KC_MUTE, KC_VOLD, KC_VOLU, KC_NO, KC_NO, KC_SLEP,
        KC_TRNS, KC_TRNS, KC_TRNS
    ),
    [_RESET] = LAYOUT_reviung39(
        RESET, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, 	TO(0), KC_NO, KC_NO, KC_NO, KC_NO, DEBUG,
        KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, 	KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO,
        KC_TRNS, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, 	KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO,
        KC_NO, KC_NO, KC_NO
    )
};

layer_state_t layer_state_set_user(layer_state_t state) {
    switch (get_highest_layer(state)) {
    case _RAISE:
        rgblight_setrgb (0x00,  0x00, 0xFF);
        break;
    case _RESET:
        rgblight_setrgb (0xFF,  0x00, 0x00);
        break;
    case _LOWER:
        rgblight_setrgb (0x00,  0xFF, 0x00);
        break;
    case _ADJUST:
        rgblight_setrgb (0x7A,  0x00, 0xFF);
        break;
    default: //  for any other layers, or the default layer
        rgblight_setrgb (0x1F,  0x2E, 0xFF);
        break;
    }

  return update_tri_layer_state(state, _LOWER, _RAISE, _ADJUST);
}
